- name: CI Requirements
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch. Please refer to https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/.
      when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
          - cuda_version: "{{ cuda_version }}"
          - cudnn_version: "{{ cudnn_version }}"
          - tensorrt_version: "{{ tensorrt_version }}"
  roles:
    # Autoware base dependencies
    - role: autoware.dev_env.rmw_implementation
    - role: autoware.dev_env.gdown
    - role: autoware.dev_env.kisak_mesa
    - role: autoware.dev_env.pacmod
    - role: autoware.dev_env.build_tools
    - role: autoware.dev_env.geographiclib
    - role: autoware.dev_env.cuda
    - role: autoware.dev_env.tensorrt
    - role: autoware.dev_env.dev_tools
    - role: autoware.dev_env.ros2_dev_tools

